import { Product } from "@/types/products";

export const WHATSFLOW_PRODUCTS: Product[] = [
  {
    id: "prod_001",
    name: "Plano Solo Pro",
    category: "plan_base",
    type: "recurring",
    status: "active",
    price: 259,
    billingCycle: "monthly",
    description: "Plano individual para começar com WhatsApp Business API",
    includes: { devicesWeb: 1, devicesMeta: 1, attendants: 1, aiAgents: 0 },
    features: [
      "1 Dispositivo API Web WhatsApp",
      "1 Dispositivo API Business Manager Meta (bônus)",
      "1 Atendente incluído",
      "Suporte padrão incluído",
    ],
    cogs: 50,
    supportCost: 20,
    laborCost: 0,
    salesCommission: 0,
    activeCustomers: 80,
    mrr: 20720,
    totalRevenue: 0,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    id: "prod_002",
    name: "Plano Profissional",
    category: "plan_base",
    type: "recurring",
    status: "active",
    price: 359,
    billingCycle: "monthly",
    description: "Plano completo para empresas em crescimento",
    includes: { devicesWeb: 1, devicesMeta: 1, attendants: 3, aiAgents: 0 },
    features: [
      "1 Dispositivo API Web WhatsApp",
      "1 Dispositivo API Business Manager Meta (bônus)",
      "3 Atendentes incluídos",
      "Suporte prioritário incluído",
    ],
    cogs: 70,
    supportCost: 25,
    laborCost: 0,
    salesCommission: 0,
    activeCustomers: 112,
    mrr: 40208,
    totalRevenue: 0,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    id: "prod_003",
    name: "Agentes de I.A.",
    category: "addon_technology",
    type: "recurring",
    status: "active",
    price: 350,
    billingCycle: "monthly",
    description: "Automação inteligente com até 5 agentes de I.A.",
    features: [
      "Até 5 agentes de I.A. inclusos",
      "Integração com ChatGPT/OpenAI",
      "Respostas automáticas inteligentes",
      "Treinamento personalizado de agentes",
      "Análise de sentimento",
      "Aprendizado contínuo",
    ],
    cogs: 150,
    supportCost: 30,
    laborCost: 0,
    salesCommission: 10,
    activeCustomers: 25,
    mrr: 8750,
    totalRevenue: 0,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    id: "prod_004",
    name: "Facilite Whatsflow Básico",
    category: "service_support",
    type: "recurring",
    status: "active",
    price: 250,
    billingCycle: "monthly",
    hourlyRate: 31.25,
    monthlyHours: 8,
    weeklyHours: 2,
    description: "Profissional dedicado para gerenciar sua conta Whatsflow (8 horas mensais)",
    features: [
      "8 horas mensais de suporte (2h/semana)",
      "Configuração e manutenção de grupos",
      "Criação de mensagens automáticas",
      "Criação de campanhas básicas",
      "Suporte operacional",
    ],
    limitations: [
      "Não inclui criação de copy's e estratégias de conteúdo",
      "Não inclui programação customizada",
      "Não inclui desenvolvimento de APIs externas",
    ],
    cogs: 0,
    laborCost: 100,
    supportCost: 0,
    salesCommission: 0,
    activeCustomers: 15,
    mrr: 3750,
    totalRevenue: 0,
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    id: "prod_005",
    name: "Facilite Whatsflow Intermediário",
    category: "service_support",
    type: "recurring",
    status: "active",
    price: 700,
    billingCycle: "monthly",
    hourlyRate: 35,
    monthlyHours: 20,
    weeklyHours: 5,
    description: "Profissional dedicado para gerenciar sua conta Whatsflow (20 horas mensais)",
    features: [
      "20 horas mensais de suporte (5h/semana)",
      "Gestão completa de campanhas",
      "Criação de fluxos de mensagens complexos",
      "Implementação de integrações (CRM, checkout, etc)",
      "Monitoramento e otimização contínua",
      "Suporte estratégico",
    ],
    limitations: [
      "Não inclui criação de copy's e estratégias de conteúdo",
      "Não inclui programação customizada",
      "Não inclui desenvolvimento de APIs externas",
    ],
    cogs: 0,
    laborCost: 250,
    supportCost: 0,
    salesCommission: 0,
    activeCustomers: 8,
    mrr: 5600,
    totalRevenue: 0,
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    id: "prod_006",
    name: "Facilite Whatsflow Avançado",
    category: "service_support",
    type: "recurring",
    status: "active",
    price: 1500,
    billingCycle: "monthly",
    hourlyRate: 37.5,
    monthlyHours: 40,
    weeklyHours: 10,
    description: "Profissional dedicado full-time para gerenciar sua conta Whatsflow (40 horas mensais)",
    features: [
      "40 horas mensais de suporte (10h/semana)",
      "Gestão estratégica completa da conta",
      "Implementação de automações complexas",
      "Integração com múltiplas ferramentas externas",
      "Desenvolvimento de fluxos avançados no Typebot",
      "Análise detalhada de performance",
      "Relatórios mensais de métricas",
      "Suporte prioritário",
    ],
    limitations: [
      "Não inclui criação de copy's e estratégias de conteúdo",
      "Não inclui programação customizada avançada",
      "Não inclui desenvolvimento de APIs externas complexas",
    ],
    cogs: 0,
    laborCost: 500,
    supportCost: 0,
    salesCommission: 0,
    activeCustomers: 3,
    mrr: 4500,
    totalRevenue: 0,
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    id: "prod_007",
    name: "Implantação Starter",
    category: "service_onetime",
    type: "one_time",
    status: "active",
    price: 2000,
    billingCycle: "one_time",
    deliveryTime: "15 dias úteis",
    description: "Implantação intermediária com configuração completa de campanhas, grupos e automações",
    features: [
      "Configuração do Portfólio Empresarial na META",
      "Criação de até 10 Campanhas de Envio em Massa",
      "Orientação sobre boas práticas de disparo",
      "Configuração de Grupos Estratégicos",
      "Criação de 10 Fluxos no Typebot",
      "Agendamento de até 3 mensagens",
      "Checklist de Conteúdos no Google Drive",
    ],
    limitations: [
      "Cliente deve fornecer copy's, listas de leads e criativos",
      "Cliente deve entregar materiais nos prazos definidos",
      "Não inclui criação de conteúdo",
      "Não inclui design de criativos",
    ],
    cogs: 0,
    laborCost: 800,
    supportCost: 0,
    salesCommission: 0,
    activeCustomers: 0,
    mrr: 0,
    totalRevenue: 24000,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
];
