-- Manual articles for features implemented since 2026-04-05
-- Rendered in /sistema/manual as carousel slides

INSERT INTO manual_articles (category, title, slug, content, order_index, is_active)
VALUES
-- Modelos de Mensagem
('whatsapp', 'Modelos de Mensagem — 3 em 1', 'modelos-mensagem', E'# Modelos de Mensagem\n\nGerencie Msgs Rápidas, Cadência e Templates HSM em um único lugar.\n\n---\n\n## O que resolve?\n\nSua equipe perde tempo digitando as mesmas respostas. Com modelos, cada atendente economiza **30 minutos/dia** e mantém a comunicação padronizada.\n\n---\n\n## Pré-requisitos\n\n- Ter pelo menos 1 instância WhatsApp conectada\n- Estar na Caixa de Entrada → Modelos de Msgs\n\n---\n\n## Passo a passo\n\n### Msgs Rápidas\n1. Clique em **+ Novo Modelo**\n2. Defina título, atalho (ex: /ola) e texto\n3. Escolha visibilidade: Todos, Setor ou Exclusivo\n4. No chat, digite **/** e selecione o modelo\n5. O texto é **editável antes do envio**\n\n### Cadência de Msgs\n1. Clique em **+ Nova Cadência**\n2. Adicione etapas: texto, imagem, áudio ou vídeo\n3. Defina o delay entre cada etapa\n4. Ative "Parar ao responder"\n\n### Templates HSM\n1. Crie templates para a API Meta Cloud\n2. Aguarde aprovação do Meta (24-48h)\n\n---\n\n## Boas práticas\n\n- Use atalhos curtos: /ola, /preco, /orcamento\n- Cadência ideal: 3-5 etapas, intercalando texto e mídia\n- Sempre deixe um próximo passo claro na última etapa\n\n**Erro comum:** Criar cadências muito longas (>7 etapas). O cliente perde interesse.', 20, true),

-- Extrator de Despesas por IA
('financeiro', 'Extrator de Despesas por IA', 'extrator-despesas-ia', E'# Extrator de Despesas por IA\n\nEnvie uma foto da nota fiscal e a IA preenche tudo automaticamente.\n\n---\n\n## O que resolve?\n\nDigitar despesas manualmente é lento e propenso a erros. Com o extrator, basta fotografar o comprovante — fornecedor, valor, data e categoria são extraídos em segundos.\n\n---\n\n## Pré-requisitos\n\n- Módulo de Despesas ativo\n- Configuração de IA ativa (OpenAI ou Anthropic)\n\n---\n\n## Passo a passo\n\n1. Acesse **Despesas** no menu Financeiro\n2. Clique em **Assistente IA** (botão roxo)\n3. Arraste ou selecione a foto da NF/comprovante\n4. Clique **Processar com IA**\n5. Revise os dados extraídos (editáveis)\n6. Clique **Salvar Despesa**\n\nVia WhatsApp: envie a foto com a legenda "Despesa" e o assistente autônomo faz tudo sozinho.\n\n---\n\n## Boas práticas\n\n- Fotos com boa iluminação aumentam a precisão\n- Confira sempre o valor antes de salvar\n- Use categorias consistentes para relatórios melhores\n\n**Erro comum:** Foto cortada ou desfocada. A IA precisa ver o valor total e o CNPJ.', 21, true),

-- Google Calendar
('configuracoes', 'Google Calendar — Sincronização', 'google-calendar', E'# Google Calendar\n\nSincronize atividades com sua agenda Google automaticamente.\n\n---\n\n## O que resolve?\n\nAtividades criadas no CRM não aparecem na sua agenda, e reuniões do Google não viram tarefas no sistema. Com a integração, tudo sincroniza automaticamente.\n\n---\n\n## Pré-requisitos\n\n- Administrador do Partner configurou as credenciais Google (Configurações do Partner)\n- Ter uma conta Google (pessoal ou corporativa)\n\n---\n\n## Passo a passo\n\n1. Acesse **Integrações → Automação**\n2. No card Google Calendar, clique **Conectar com Google**\n3. Autorize o acesso na tela do Google\n4. Configure os toggles:\n   - Whatsflow → Google (atividades viram eventos)\n   - Google → Whatsflow (eventos viram atividades)\n   - Google Meet automático\n5. Clique **Sincronizar agora** para primeira sync\n\n---\n\n## Boas práticas\n\n- Cada membro da equipe conecta sua própria agenda\n- Use "Google Meet automático" para reuniões\n- Sincronize antes de reuniões importantes\n\n**Erro comum:** Esquecer de ativar os toggles após conectar. Sem toggles, nada sincroniza.', 22, true),

-- Dashboard de Qualidade
('whatsapp', 'Dashboard de Qualidade — Auditor IA', 'dashboard-qualidade', E'# Dashboard de Qualidade\n\nA IA audita suas conversas e gera scores de atendimento por critério.\n\n---\n\n## O que resolve?\n\nSem dados de qualidade, o gestor não sabe quem atende bem e quem precisa de treinamento. Com o auditor, cada conversa recebe nota de 0 a 10 em 6 critérios.\n\n---\n\n## Pré-requisitos\n\n- Módulo de IA ativo\n- Pelo menos 1 conversa finalizada para auditoria\n\n---\n\n## Passo a passo\n\n1. Acesse **Caixa de Entrada → Métricas**\n2. Role até **Qualidade do Atendimento**\n3. Analise:\n   - **Score Geral** — média da equipe\n   - **Ranking de Concierges** — quem está melhor\n   - **Critérios** — onde a equipe é fraca\n   - **Erros frequentes** — padrões de erro\n4. Ajuste o período (7d, 30d, 90d)\n\n### Classificação\n- ≥9.0 — Concierge Elite\n- ≥8.0 — Concierge\n- ≥7.0 — Vendedor\n- <7.0 — Em Treinamento\n\n---\n\n## Boas práticas\n\n- Revise semanalmente com a equipe\n- Foque no critério com barra MAIS CURTA\n- Use o ranking para distribuir leads VIP\n\n**Erro comum:** Ignorar os "Erros Mais Frequentes". Eles mostram exatamente onde treinar.', 23, true),

-- Previsibilidade Financeira
('financeiro', 'Motor de Previsibilidade Financeira', 'previsibilidade-financeira', E'# Motor de Previsibilidade\n\nProjeção automática de 12 meses com provisionamento de 13º e férias.\n\n---\n\n## O que resolve?\n\nEmpresas são surpreendidas por despesas de final de ano (13º, férias). O motor calcula automaticamente essas provisões baseado na sua folha de pagamento real.\n\n---\n\n## Pré-requisitos\n\n- Ter despesas cadastradas na categoria "Pessoal"\n- Marcar despesas de folha como "Recorrente"\n\n---\n\n## Como funciona\n\n1. Acesse **Despesas**\n2. O painel de Previsibilidade aparece automaticamente no topo\n3. Mostra:\n   - **Próximos 30 dias** — despesas pendentes\n   - **Saúde Financeira** — semáforo (Saudável/Atenção/Risco)\n   - **Projeção Anual** — com 13º e férias provisionados\n4. Gráfico de barras: dados reais (azul) vs. projeção (tracejado)\n\n### Cálculo automático\n- **13º:** média mensal de "Pessoal" ÷ 12\n- **Férias:** 33,3% da folha mensal ÷ 12\n\n---\n\n## Boas práticas\n\n- Mantenha despesas recorrentes sempre marcadas\n- Revise mensalmente se novas contratações alteraram a folha\n\n**Erro comum:** Não categorizar despesas como "Pessoal". Sem categoria correta, o cálculo fica zerado.', 24, true)

ON CONFLICT (slug) DO UPDATE SET
  content = EXCLUDED.content,
  title = EXCLUDED.title,
  order_index = EXCLUDED.order_index,
  updated_at = now();
